import { Col, Image, Row } from 'antd'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

const whitePieces = [
  {
    id: 'white-khun',
    name: 'Khun',
    image: '/chesses/white_khun.svg',
  },
  {
    id: 'white-met',
    name: 'Met',
    image: '/chesses/white_met.svg',
  },
  {
    id: 'white-ma',
    name: 'Ma',
    image: '/chesses/white_ma.svg',
  },
  {
    id: 'white-ruea',
    name: 'Ruea',
    image: '/chesses/white_ruea.svg',
  },
  {
    id: 'white-khon',
    name: 'Khon',
    image: '/chesses/white_khon.svg',
  },
  {
    id: 'white-bia',
    name: 'Bia',
    image: '/chesses/white_bia.svg',
  },
]

const blackPieces = [
  {
    id: 'black-khun',
    name: 'Khun',
    image: '/chesses/black_khun.svg',
  },
  {
    id: 'black-met',
    name: 'Met',
    image: '/chesses/black_met.svg',
  },
  {
    id: 'black-ma',
    name: 'Ma',
    image: '/chesses/black_ma.svg',
  },
  {
    id: 'black-ruea',
    name: 'Ruea',
    image: '/chesses/black_ruea.svg',
  },
  {
    id: 'black-khon',
    name: 'Khon',
    image: '/chesses/black_khon.svg',
  },
  {
    id: 'black-bia',
    name: 'Bia',
    image: '/chesses/black_bia.svg',
  },
]

export default function Home() {
  const [chessBoard, setChessBoard] = useState<
    Array<Array<string | null>>
  >([
    [
      'black-ruea',
      'black-ma',
      'black-khon',
      'black-met',
      'black-khun',
      'black-khon',
      'black-ma',
      'black-ruea',
    ],
    [null, null, null, null, null, null, null, null],
    [
      'black-bia',
      'black-bia',
      'black-bia',
      'black-bia',
      'black-bia',
      'black-bia',
      'black-bia',
      'black-bia',
    ],
    [null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null],
    [
      'white-bia',
      'white-bia',
      'white-bia',
      'white-bia',
      'white-bia',
      'white-bia',
      'white-bia',
      'white-bia',
    ],
    [null, null, null, null, null, null, null, null],
    [
      'white-ruea',
      'white-ma',
      'white-khon',
      'white-khun',
      'white-met',
      'white-khon',
      'white-ma',
      'white-ruea',
    ],
  ])
  const [selectedPiece, setSelectedPiece] = useState<
    string | null
  >(null)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{ width: 640, backgroundColor: '#fff' }}>
          {Array.from({ length: 8 }).map((_, i) => (
            <Row key={i}>
              {Array.from({ length: 8 }).map((_, j) => {
                // convert to chess notation
                const letter = String.fromCharCode(
                  97 + j,
                ).toUpperCase()

                // get image of the piece
                const pieceId = chessBoard[i][j]
                  ? chessBoard[i][j]
                  : null

                // get the piece object
                const pieceObject = pieceId
                  ? whitePieces.find(
                      (item) => item.id === pieceId,
                    ) ||
                    blackPieces.find(
                      (item) => item.id === pieceId,
                    )
                  : null

                return (
                  <Col
                    key={`${letter}-${8 - i}`}
                    span={3}
                    style={{
                      border: '1px solid #000',
                      height: 80,
                      width: 80,
                      display: 'flex',
                      justifyContent: 'center',
                      alignItems: 'center',
                    }}>
                    {pieceObject && (
                      <Image
                        preview={false}
                        alt="chess"
                        width={40}
                        height={40}
                        src={pieceObject.image}
                      />
                    )}
                  </Col>
                )
              })}
            </Row>
          ))}
        </div>
      </main>
    </>
  )
}
